title: um.wtf
email: vesche@protonmail.com
description: <a href='/index'>Home</a> | <a href='/articles'>My Articles</a> | <a href='mailto:vesche@protonmail.com'>Email</a>
url: "https://um.wtf"
theme: jekyll-theme-hacker

plugins:
  - jekyll-octicons

github:
  is_project_page: false
